config/routes.rb
PureNotifier::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/:provider/errback', to: 'sessions#fail'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :subscriptions, only: [:index, :create, :destroy]

  authenticate do
    mount Resque::Server, :at => "/admin/resque"
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :pull_request
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  scope :not_merged, -> { where(merged_at: nil) }

  def create_notifications
    subscribers.each do |subscriber|
      attributes = {pull_request_id: id, user_id: subscriber.id}
      Notification.find_or_create_by(attributes)
    end
  end

  def short_name
    # TODO move to some kind of presenter object
    "#{repo_owner_login}/#{repo_name} ##{number}"
  end
  alias :to_s :short_name

  def has_metadata?
    !title.nil?
  end

  def open?
    merged_at.nil?
  end

  def merged?
    !open?
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :pull_request

  default_scope -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subscriptions, dependent: :delete_all
  has_many :notifications, dependent: :delete_all

  has_many :watched_pull_requests, through: :subscriptions, source: :pull_request
  has_many :pending_pull_requests, through: :notifications, source: :pull_request

  def has_pending_pull_requests?
    pending_pull_requests.count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :signed_in?

  def index
    @user_login = if signed_in?
                    current_user.login
                  end
  end

  def signed_in?
    !current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = UserBuilder.new.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in."
  end

  def fail
    redirect_to root_url, alert: "Sign in failed!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out."
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def index
    @subscriptions = subscription_manager.list
  end

  def create
    subscription_manager.add_url params[:url]
    flash[:notice] = "Subscription added."
    redirect_to subscriptions_url
  rescue PullRequestHtmlUrl::ParsingError
    flash[:alert] = "Cannot add pull request: URL is invalid."
    redirect_to subscriptions_url
  rescue SubscriptionManager::AlreadySubscribed
    flash[:alert] = "Cannot add pull request: you have already subscribed!"
    redirect_to subscriptions_url
  end

  def destroy
    subscription_manager.remove_id params[:id]
    flash[:notice] = "Subscription removed."
    redirect_to subscriptions_url
  end

  private

  def subscription_manager
    SubscriptionManager.new(current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/application/_navbar.html.haml
= nav_bar do
  = menu_group do
    = menu_item "Home", root_path
    - if current_user
      = menu_item "Subscriptions", subscriptions_path
  = menu_group pull: :right do
    - if current_user
      = menu_item "Sign out", signout_path
    - else
      = menu_item "Sign in", "/auth/github"

app/views/home/_welcome_back.html.haml
%p
  Welcome back
  %span= "#{@user_login}!"

%p
  You want to be notified when a pull request is merged?
  = link_to "Manage your subscriptions!", subscriptions_path

app/views/home/_welcome_new.html.haml
%p
  Tired of polling open pull requests to see if one of them has been closed?
  We can help!
  Just add GitHub URLs of pull requests you care about,
  and we will notify you by email as soon as they are merged.

%p
  All you need is a GitHub account!

= button_to "Sign in with GitHub", '/auth/github', class: %w{btn btn-primary}

app/views/home/index.html.haml
%h1
  Pull Request Notifier

- if signed_in?
  = render 'welcome_back'
- else
  = render 'welcome_new'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Pull Request Notifier"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    = render 'navbar'

    .container

      .row
        .span8
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Tech-Angels 2013

app/views/layouts/email.html.haml
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', :'http-equiv' => 'Content-Type'}
  %body
    = yield

app/views/layouts/email.text.erb
<%= yield %>

app/views/pull_requests/_pull_request.html.haml
.pull_request
  %h3= pull_request.short_name
  - if pull_request.has_metadata?
    %h4= pull_request.title
    = pull_request.body
    %a{href: pull_request.html_url}
      Read on GitHub
  - else
    .url= pull_request.url
    .notice loading...

app/views/subscriptions/_subscription.html.haml
.subscription
  = render subscription.pull_request
  - if subscription.pull_request.merged?
    %p
      This pull request has been merged and the watch can be safely removed.
    %p
      = button_to "Remove", subscription_path(subscription.id), method: :delete, class: %w{btn}
  - else
    %p
      = button_to "Remove", subscription_path(subscription.id), method: :delete, class: %w{btn btn-danger}

app/views/subscriptions/index.html.haml
= render template: 'subscriptions/new'

- unless @subscriptions.empty?
  %h2 Your Pull Requests
  %p Here are the pull requests you are currently watching:
  = render @subscriptions

app/views/subscriptions/new.html.haml
%h2 Add a Pull Request

%p Visit GitHub.com and copy the URL of the pull request you want to monitor.
= form_tag subscriptions_path, method: :post, class: %w{form-inline} do
  = field_set_tag do
    = label_tag :url, 'Pull Request URL:'
    = url_field_tag :url, nil, size: 60, placeholder: 'https://github.com/resque/resque/pull/1135'
    = submit_tag 'Add', class: %w{btn btn-primary}